name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: sudo apt update | sudo apt install -y cowsay
      - run: cat README.md | cowsay