name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: docker image build --tag="node-linter" ./
      - run: docker container run node-linter npm run lint