name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: docker image build --tag="nodeLinter" ./
      - run: docker container run nodeLinter npm run build